name: Running front tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/front-tests.yml'
      - 'front/**'
      - 'common/**'


defaults:
  run:
    working-directory: ./front

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./front/package-lock.json
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format:check
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./front/package-lock.json
      - name: Install packages
        run: npm ci
      - name: Run test
        run: npm run test
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./front/package-lock.json
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
